// Generated by delombok at Sat Oct 12 00:30:19 BRT 2024
package com.tiduswr.view;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;

import javax.swing.BorderFactory;
import javax.swing.JPanel;

import com.tiduswr.model.Player;
import com.tiduswr.model.PlayerCardData;

/**
 * Componente que representa as cartas de um jogador em uma interface de jogo.
 * Permite a seleção e a interação com as cartas na mão do jogador.
 */
public class PlayerCards extends JPanel {
    /**
     * Jogador associado a estas cartas
     */
    private Player player;
    /**
     * Número de cartas na mão
     */
    private int handSize = 5;
    /**
     * Indica se as cartas estão ativas para seleção
     */
    private boolean cardsActive = true;
    /**
     * Índice da carta selecionada
     */
    private int selectedIndex;

    /**
     * Construtor da classe PlayerCards.
     * Inicializa o painel com as cartas do jogador e configura os ouvintes de
     * eventos.
     *
     * @param father A interface do jogo que contém este componente.
     * @param player O jogador associado a estas cartas.
     * @param width  Largura preferida do painel.
     * @param height Altura preferida do painel.
     */
    public PlayerCards(TripleTriadUI father, Player player, int width, int height) {
        this.player = player;
        selectedIndex = -1;
        setLayout(new GridLayout(5, 1)); // Layout em grade para as cartas
        setPreferredSize(new Dimension(width, height)); // Define o tamanho preferido
        // Adiciona componentes de carta ao painel
        for (int i = 0; i < handSize; i++) {
            var index = i;
            var cardData = player.getCards().get(index);
            var playerCardData = new PlayerCardData(cardData, player, 0, false);
            var cardComponent = new CardComponent(playerCardData, e -> {
                if (!cardsActive || playerCardData.isFlipped())
                    return;
                father.getGameLog().addLogMessage(String.format("A carta \'%s\' foi selecionada!", cardData.getName()));
                father.getSoundServices().getSoundService("selection").play();
                selectedIndex = player.getCards().indexOf(cardData);
                updateBorders();
            });
            add(cardComponent);
        }
        setBorder(BorderFactory.createTitledBorder(getPlayer().getName()));
        // Listener para resetar seleção ao clicar fora das cartas
        father.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (!contains(e.getPoint()) && selectedIndex != -1 && cardsActive) {
                    selectedIndex = -1;
                    updateBorders();
                }
            }
        });
        // Exemplo de passar uma carta da mão para o campo
        father.getBoard().addPositionListener((row, col) -> {
            var selected = getSelected();
            if (selected != null) {
                if (!father.getBoard().addCard(selected, row, col)) {
                    father.getSoundServices().getSoundService("error").play();
                    father.getGameLog()
                            .addLogMessage(String.format("A posição [%d, %d] já possui uma carta!", row, col));
                } else {
                    father.getSoundServices().getSoundService("card-placed").play();
                    removeSelected();
                    father.addTurn();
                    father.switchTurn();
                }
            }
        });
    }

    /**
     * Define se as cartas estão ativas para seleção.
     *
     * @param enabled True para ativar a seleção de cartas, false para desativar.
     */
    public void setCardsActive(boolean enabled) {
        this.cardsActive = enabled;
    }

    /**
     * Atualiza as bordas das cartas com base na seleção atual.
     */
    private void updateBorders() {
        for (int i = 0; i < handSize; i++) {
            var cardComponent = (CardComponent) getComponent(i);
            cardComponent.setCardIsSelected(i == selectedIndex); // Destaca a carta selecionada
        }
        revalidate();
        repaint();
    }

    /**
     * Obtém a carta atualmente selecionada.
     *
     * @return A carta selecionada, ou null se nenhuma carta estiver selecionada.
     */
    public PlayerCardData getSelected() {
        if (selectedIndex != -1) {
            return ((CardComponent) getComponent(selectedIndex)).getInfo();
        }
        return null;
    }

    /**
     * Remove a carta atualmente selecionada da mão do jogador.
     *
     * @return True se uma carta foi removida, false caso contrário.
     */
    public boolean removeSelected() {
        var selected = getSelected();
        if (selected == null)
            return false;
        CardComponent selectedCard = (CardComponent) getComponent(selectedIndex);
        player.getCards().removeIf(card -> card.equals(selectedCard.getInfo().getCardData()));
        selectedIndex = -1;
        handSize--;
        remove(selectedCard);
        revalidate();
        repaint();
        return true;
    }

    /**
     * Obtém uma lista de todos os dados das cartas do jogador.
     *
     * @return Uma lista de objetos PlayerCardData.
     */
    private List<PlayerCardData> getAllPlayerCardData() {
        List<PlayerCardData> cardDataList = new ArrayList<>();
        for (int i = 0; i < getComponentCount(); i++) {
            CardComponent cardComponent = (CardComponent) getComponent(i);
            cardDataList.add(cardComponent.getInfo());
        }
        return cardDataList;
    }

    /**
     * Processa todos os dados das cartas do jogador, aplicando uma ação a cada um.
     *
     * @param action A ação a ser aplicada, representada como um BiConsumer que
     *               recebe o índice e os dados da carta.
     */
    public void processAllPlayerCardData(BiConsumer<Integer, PlayerCardData> action) {
        var cards = getAllPlayerCardData();
        for (int i = 0; i < cards.size(); i++) {
            action.accept(i, cards.get(i));
        }
        revalidate();
        repaint();
    }

    /**
     * Obtém o jogador associado a estas cartas.
     *
     * @return O jogador que possui estas cartas.
     */
    public Player getPlayer() {
        return this.player;
    }

    /**
     * Obtém o número de cartas na mão do jogador.
     *
     * @return O número de cartas na mão.
     */
    public int getHandSize() {
        return this.handSize;
    }

    /**
     * Verifica se as cartas estão ativas para seleção.
     *
     * @return True se as cartas estiverem ativas para seleção, caso contrário,
     *         false.
     */
    public boolean isCardsActive() {
        return this.cardsActive;
    }

    /**
     * Obtém o índice da carta atualmente selecionada.
     *
     * @return O índice da carta selecionada.
     */
    public int getSelectedIndex() {
        return this.selectedIndex;
    }
    
    public void rules(TripleTriadUI father, int row, int col){
        var cardPlaced = getSelected();
        
        int sumRg = 0;
        int sumLf = 0;
        int sumUp = 0;
        int sumDw = 0;

        if(father.getBoard().getBoardCards()[row][col+1] != null){
            sumRg = cardPlaced.getCardData().getRight() + father.getBoard().getBoardCards()[row][col+1].getInfo().getCardData().getLeft();
        }
        if(father.getBoard().getBoardCards()[row][col-1] != null){
            sumLf = cardPlaced.getCardData().getLeft() + father.getBoard().getBoardCards()[row][col-1].getInfo().getCardData().getRight();
        }
        if(father.getBoard().getBoardCards()[row-1][col] != null){
            sumUp = cardPlaced.getCardData().getUp() + father.getBoard().getBoardCards()[row-1][col].getInfo().getCardData().getDown();
        }
        if(father.getBoard().getBoardCards()[row+1][col] != null){
            sumDw = cardPlaced.getCardData().getDown() + father.getBoard().getBoardCards()[row+1][col].getInfo().getCardData().getUp();
        }

        if(sumRg == sumUp && sumRg != 0 && sumUp != 0){}
            if(father.getBoard().getBoardCards()[row-1][col].getInfo().getOwner() != player){
                father.getBoard().getBoardCards()[row-1][col].getInfo().setOwner(player);
            }    
            if(tabuleiro.mat[linha][coluna+1].dono != carta.dono){
                tabuleiro.mat[linha][coluna+1].dono = carta.dono
            }
        }
        if(somaEq == somaBx and somaEq != 0 and somaBx != 0):
            if(tabuleiro.mat[linha][coluna-1].dono != carta.dono):
                tabuleiro.mat[linha][coluna-1].dono = carta.dono

            if(tabuleiro.mat[linha+1][coluna].dono != carta.dono):
                tabuleiro.mat[linha+1][coluna].dono = carta.dono

        if(not (tabuleiro.mat[linha][coluna+1] == None)):
            if(carta.dir > tabuleiro.mat[linha][coluna+1].esq and carta.dono != tabuleiro.mat[linha][coluna+1].dono):
                tabuleiro.mat[linha][coluna+1].dono = carta.dono
                if(carta.dono >= 1 ):
                    self.jogadores[1].pontos += 1
                    self.jogadores[0].pontos -= 1
                else: 
                    self.jogadores[0].pontos += 1
                    self.jogadores[1].pontos -= 1
                
        
        if(not (tabuleiro.mat[linha][coluna-1] == None)):
            if(carta.esq > tabuleiro.mat[linha][coluna-1].dir and carta.dono != tabuleiro.mat[linha][coluna-1].dono):
                tabuleiro.mat[linha][coluna-1].dono = carta.dono
                if(carta.dono >= 1 ):
                    self.jogadores[1].pontos += 1
                    self.jogadores[0].pontos -= 1
                else: 
                    self.jogadores[0].pontos += 1
                    self.jogadores[1].pontos -= 1
                    
        if(not (tabuleiro.mat[linha-1][coluna] == None)):        
            if(carta.cima > tabuleiro.mat[linha-1][coluna].baixo and carta.dono != tabuleiro.mat[linha-1][coluna].dono):
                tabuleiro.mat[linha-1][coluna].dono = carta.dono
                if(carta.dono >= 1 ):
                    self.jogadores[1].pontos += 1
                    self.jogadores[0].pontos -= 1
                else: 
                    self.jogadores[0].pontos += 1
                    self.jogadores[1].pontos -= 1
                    
        if(not (tabuleiro.mat[linha+1][coluna] == None)):        
            if(carta.baixo > tabuleiro.mat[linha+1][coluna].cima and carta.dono != tabuleiro.mat[linha+1][coluna].dono):
                tabuleiro.mat[linha+1][coluna].dono = carta.dono
                if(carta.dono >= 1 ):
                    self.jogadores[1].pontos += 1
                    self.jogadores[0].pontos -= 1
                else: 
                    self.jogadores[0].pontos += 1
                    self.jogadores[1].pontos -= 1
    }
}
